### PR TITLE
feat(CO-627): remove briefcase

### PR DESCRIPTION
**Pull request by Polpetta**
Please check carefully because I really don't know how this migration mechanism works

### CODE REVIEW

**Review by frisonisland — APPROVED** [review]

**Review by frisonisland — APPROVED** [review]

**Review by aheeva-yuliya — APPROVED** [review]

**Comment by Polpetta** [comment]
> > Please check carefully because I really don't know how this migration mechanism works
> 
> The migration mechanism works manually currently. In past it was managed by this: https://github.com/Zimbra/zm-build/blob/4c7a1f143b2b23c2e7ca03e037ec0cb267738545/rpmconf/Upgrade/zmupgrade.pm So, to apply a migration you have to run "perl path/to/script.pl". We should just check what is the current DB version in the system to be extra careful slightly_smiling_face

When running the script manually I get the following error:
```shell
./libexec/scripts/migrate20230329-BriefcaseRemoval.pl 
Can't locate Migrate.pm in @INC (you may need to install the Migrate module) (@INC contains: /opt/zextras/common/lib/perl5/x86_64-linux-gnu-thread-multi /opt/zextras/common/lib/perl5/x86_64-linux-gnu-thread-multi /opt/zextras/common/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./libexec/scripts/migrate20230329-BriefcaseRemoval.pl line 14.
BEGIN failed--compilation aborted at ./libexec/scripts/migrate20230329-BriefcaseRemoval.pl line 14.
```

**Comment by keshavbhatt** [comment]
> When running the script manually I get the following error:
> 
> ```shell
> ./libexec/scripts/migrate20230329-BriefcaseRemoval.pl 
> Can't locate Migrate.pm in @INC (you may need to install the Migrate module) (@INC contains: /opt/zextras/common/lib/perl5/x86_64-linux-gnu-thread-multi /opt/zextras/common/lib/perl5/x86_64-linux-gnu-thread-multi /opt/zextras/common/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./libexec/scripts/migrate20230329-BriefcaseRemoval.pl line 14.
> BEGIN failed--compilation aborted at ./libexec/scripts/migrate20230329-BriefcaseRemoval.pl line 14.
> ```

This is due to the missing Migration module. But why it is missing? Are you trying on custom environment where some carbonio-* packages may be missing?

**Comment by Polpetta** [comment]
Nope, I tried putting the script in `/opt/libexec/scripts/` (where the other script for migration are kept) and I've run it with `zextras` user. I've set the file as executable but that's it :thinking:

**Comment by frisonisland** [comment]
> When running the script manually I get the following error:
> 
> ```shell
> ./libexec/scripts/migrate20230329-BriefcaseRemoval.pl 
> Can't locate Migrate.pm in @INC (you may need to install the Migrate module) (@INC contains: /opt/zextras/common/lib/perl5/x86_64-linux-gnu-thread-multi /opt/zextras/common/lib/perl5/x86_64-linux-gnu-thread-multi /opt/zextras/common/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./libexec/scripts/migrate20230329-BriefcaseRemoval.pl line 14.
> BEGIN failed--compilation aborted at ./libexec/scripts/migrate20230329-BriefcaseRemoval.pl line 14.
> ```

I remember having a similar issues with the index locator migration. **Try to run it with the -I flag** (it is due some include logic which honestly I don't remember):
**cd /opt/zextras/libexec/scripts && perl -I. <migration name>**

**Comment by frisonisland** [comment]
@Polpetta we also have to provide/install the migration script:
- similar to this: https://github.com/Zextras/carbonio-build/commit/5ce9eb2533f67215f687e1ecf4c15644313bf235

**Review by keshavbhatt — APPROVED** [review]

**Review by aheeva-yuliya — APPROVED** [review]

**Pull request merged**
